export const CartActionTypes = {
    TRIGGER_CART_VISIBILITY: 'CART_ACTION_TYPES_TRIGGER_CART_VISIBILITY',
    HIDE_CART: "CART_ACTION_TYPES_HIDE_CART",
    ADD_ITEM: "CART_ACTION_TYPES_ADD_ITEM",
    REMOVE_ITEM: "CART_ACTION_TYPES_REMOVE_ITEMS",
    INCREASE_ITEM_QUANTITY: "CART_ACTION_TYPES_INCREASE_ITEM_QUANTITY",
    DECREASE_ITEM_QUANTITY: "CART_ACTION_TYPES_DECREASE_ITEM_QUANTITY"
}