export const ShopActionTypes = {
    SELECT_CATEGORY: "SHOP_ACTION_TYPE_SELECT_CATEGORY",
    FETCH_DATA_START: "SHOP_ACTION_TYPE_START_FETCH_DATA",
    FETCH_DATA_SUCCESS: "SHOP_ACTION_TYPE_FETCH_DATA_SUCCESS",
    FETCH_DATA_ERROR: "SHOP_ACTION_TYPE_FETCH_DATA_ERROR"
}