export const UserActionTypes = {
    SET_CURRENT_USER: "USER_ACTION_SET_CURRENT_USER",
    GOOGLE_SING_IN_START: "USER_ACTION_GOOGLE_SING_IN_START",
    GOOGLE_SING_IN_SUCCESS: "USER_ACTION_GOOGLE_SING_IN_SUCCESS",
    GOOGLE_SING_IN_FAILURE: "USER_ACTION_GOOGLE_SING_IN_FAILURE",
    EMAIL_SING_IN_START: "USER_ACTION_EMAIL_SING_IN_START",
    EMAIL_SING_IN_SUCCESS: "USER_ACTION_EMAIL_SING_IN_SUCCESS",
    EMAIL_SING_IN_FAILURE: "USER_ACTION_EMAIL_SING_IN_FAILURE",

    SIGN_OUT_START: "USER_ACTION_SIGN_OUT_START",
    SIGN_OUT_SUCCESS: "USER_ACTION_SIGN_OUT_SUCCESS",
    SIGN_OUT_FAILURE: "USER_ACTION_SIGN_OUT_FAIL"
}